ALTER TABLE T_ORDER ADD COLUMN address_type INT NOT NULL DEFAULT 0;

ALTER TABLE T_ADDRESS ADD COLUMN type INT NOT NULL DEFAULT 0;
ALTER TABLE T_ADDRESS ALTER COLUMN first_name SET NOT NULL;
ALTER TABLE T_ADDRESS ALTER COLUMN last_name SET NOT NULL;
