ALTER TABLE T_ORDER ADD COLUMN sub_total_price DECIMAL(20, 4) NOT NULL DEFAULT 0;
ALTER TABLE T_ORDER ADD COLUMN delivery_fees DECIMAL(20, 4) NOT NULL DEFAULT 0;
ALTER TABLE T_ORDER ADD COLUMN savings_amount DECIMAL(20, 4) NOT NULL DEFAULT 0;

ALTER TABLE T_ORDER_ITEM ADD COLUMN unit_comparable_price DECIMAL(20, 4);
