openapi: "3.0.0"
info:
  title: "Wutsi Order API"
  description: API for managing orders
  version: "1.0.0"

servers:
  - url: https://wutsi-order-server-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-order-server-prod.herokuapp.com
    description: Production

paths:
  /v1/orders:
    post:
      operationId: "create-order"
      description: Create an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateOrderResponse'
        403:
          description: The caller is not authorized to call this endpoint
        409:
          description: Error
      tags:
        - Order
      security:
        - api_key: [ 'order-manage' ]

  /v1/orders/{id}:
    get:
      operationId: "get-order"
      description: Get an order
      parameters:
        - in: path
          name: id
          description: ID of the category
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrderResponse'
        403:
          description: The caller is not authorized to call this endpoint
        409:
          description: Error
      tags:
        - Order
      security:
        - api_key: [ 'order-read' ]

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    CreateOrderItem:
      type: object
      properties:
        productId:
          type: integer
          format: int64
          description: ID of the product
        quantity:
          type: integer
          description: Number of offers
          minimum: 1

    CreateOrderRequest:
      type: object
      properties:
        merchantId:
          type: integer
          format: int64
          description: ID of the merchant
        items:
          type: array
          items:
            $ref: "#/components/schemas/CreateOrderItem"
          description: Items of order
      required:
        - items

    CreateOrderResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the order created

    OrderItem:
      type: object
      properties:
        productId:
          type: integer
          format: int64
          description: ID of the product
        quantity:
          type: integer
          description: Number of offers
        unitPrice:
          type: number
          format: decimal
          description: Unit price
        currency:
          type: string
          description: currency

    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the order
        merchantId:
          type: integer
          format: int64
          description: ID of the merchant
        accountId:
          type: integer
          format: int64
          description: ID of the customer
        status:
          type: string
          description: Description of teh order
        totalPrice:
          type: number
          format: double
          description: Amount
        currency:
          type: string
          description: Currency
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"
          description: Offers in the product
        created:
          type: string
          format: date-time
          description: Creation datetime
        updated:
          type: string
          format: date-time
          description: Last update

    GetOrderResponse:
      type: object
      properties:
        order:
          type: object
          $ref: "#/components/schemas/Order"
