openapi: "3.0.0"
info:
  title: "Wutsi Order API"
  description: API for managing orders
  version: "1.0.0"

servers:
  - url: https://wutsi-order-server-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-order-server-prod.herokuapp.com
    description: Production

paths:
  /v1/orders:
    post:
      operationId: "create-order"
      description: Create an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateOrderResponse'
        403:
          description: The caller is not authorized to call this endpoint
        409:
          description: Error
      tags:
        - Order
      security:
        - api_key: [ 'order-manage' ]

  /v1/orders/search:
    post:
      operationId: "search-orders"
      description: Search Orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchOrderRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchOrderResponse'
        403:
          description: The caller is not authorized to call this endpoint
      tags:
        - Order
      security:
        - api_key: [ 'order-read' ]

  /v1/orders/{id}:
    get:
      operationId: "get-order"
      description: Get an order
      parameters:
        - in: path
          name: id
          description: ID of the order
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrderResponse'
        403:
          description: The caller is not authorized to call this endpoint
        409:
          description: Error
      tags:
        - Order
      security:
        - api_key: [ 'order-read' ]

  /v1/orders/{id}/shipping-method:
    post:
      operationId: "set-shipping-method"
      description: Set Shipping Method
      parameters:
        - in: path
          name: id
          description: ID of the order
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetShippingMethodRequest'
      responses:
        200:
          description: Success
        403:
          description: The caller is not authorized to call this endpoint
      tags:
        - Order
      security:
        - api_key: [ 'order-manage' ]

  /v1/orders/{id}/shipping-address:
    post:
      operationId: "set-shipping-address"
      description: Set Shipping Address
      parameters:
        - in: path
          name: id
          description: ID of the order
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetAddressRequest'
      responses:
        200:
          description: Success
        403:
          description: The caller is not authorized to call this endpoint
      tags:
        - Order
      security:
        - api_key: [ 'order-manage' ]

  /v1/orders/{id}/status:
    post:
      operationId: "change-status"
      description: Change an order status
      parameters:
        - in: path
          name: id
          description: ID of the order
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeStatusRequest'
      responses:
        200:
          description: Success
        403:
          description: The caller is not authorized to call this endpoint
      tags:
        - Order
      security:
        - api_key: [ 'order-manage' ]

  /v1/addresses:
    get:
      operationId: "list-addresses"
      description: List the addresses of the current user
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAddressResponse'
        403:
          description: The caller is not authorized to call this endpoint
        409:
          description: Error
      tags:
        - Order
      security:
        - api_key: [ 'order-read' ]

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    CreateOrderItem:
      type: object
      properties:
        productId:
          type: integer
          format: int64
          description: ID of the product
        quantity:
          type: integer
          description: Number of offers
          minimum: 1

    CreateOrderRequest:
      type: object
      properties:
        merchantId:
          type: integer
          format: int64
          description: ID of the merchant
        items:
          type: array
          items:
            $ref: "#/components/schemas/CreateOrderItem"
          description: Items of order
      required:
        - items

    CreateOrderResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the order created

    OrderItem:
      type: object
      properties:
        productId:
          type: integer
          format: int64
          description: ID of the product
        quantity:
          type: integer
          description: Number of offers
        unitPrice:
          type: number
          format: decimal
          description: Unit price
        unitComparablePrice:
          type: number
          format: decimal
          description: Unit comparable price
          nullable: true
        currency:
          type: string
          description: currency

    Address:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the address
        firstName:
          type: string
          description: First Name
        lastName:
          type: string
          description: Last Name
        country:
          type: string
          description: Country
        street:
          type: string
          description: Street address
          nullable: true
        cityId:
          type: integer
          format: int64
          description: ID of the city
          nullable: true
        zipCode:
          type: string
          description: ZIP code
          nullable: true
        email:
          type: string
          format: email
          description: Email address
          nullable: true

    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the order
        tenantId:
          type: integer
          format: int64
          description: ID of the tenant
        merchantId:
          type: integer
          format: int64
          description: ID of the merchant
        accountId:
          type: integer
          format: int64
          description: ID of the customer
        reservationId:
          type: integer
          format: int64
          description: ID of the reservation associated with Order
          nullable: true
        status:
          type: string
          description: Description of teh order
        paymentStatus:
          type: string
          description: Status of the payment
        subTotalPrice:
          type: number
          format: double
          description: Sub Total, which is the total price of the products.
        savingsAmount:
          type: number
          format: double
          description: Savings amount. Savings are computed by summing for each product, the difference between unit price vs comparable-price
        totalPrice:
          type: number
          format: double
          description: Total price to charge to the customer
        totalPaid:
          type: number
          format: double
          description: Total amount paid by the customer
        currency:
          type: string
          description: Currency
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"
          description: Offers in the product
        created:
          type: string
          format: date-time
          description: Creation datetime
        updated:
          type: string
          format: date-time
          description: Last update
        shippingId:
          type: integer
          format: int64
          description: Shipping ID
          nullable: true
        deliveryFees:
          type: number
          format: double
          description: Delivery fees
        expectedDelivered:
          type: string
          format: date-time
          description: Expected delivery date
          nullable: true
        shippingAddress:
          type: object
          $ref: "#/components/schemas/Address"
          nullable: true

    GetOrderResponse:
      type: object
      properties:
        order:
          type: object
          $ref: "#/components/schemas/Order"

    OrderSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the order
        merchantId:
          type: integer
          format: int64
          description: ID of the merchant
        accountId:
          type: integer
          format: int64
          description: ID of the customer
        reservationId:
          type: integer
          format: int64
          description: ID of the reservation associated with Order
          nullable: true
        status:
          type: string
          description: Status of the order
        paymentStatus:
          type: string
          description: Status of the payment
        subTotalPrice:
          type: number
          format: double
          description: Sub Total, which is the total price of the products.
        deliveryFees:
          type: number
          format: double
          description: Delivery fees
        savingsAmount:
          type: number
          format: double
          description: Savings amount. Savings are computed by summing for each product, the difference between unit price vs comparable-price
        totalPrice:
          type: number
          format: double
          description: Total price to charge to the customer
        totalPaid:
          type: number
          format: double
          description: Total amount paid by the customer
        currency:
          type: string
          description: Currency
        created:
          type: string
          format: date-time
          description: Creation datetime
        updated:
          type: string
          format: date-time
          description: Last update

    SearchOrderRequest:
      type: object
      properties:
        merchantId:
          type: integer
          format: int64
          description: ID of the merchant
          nullable: true
        accountId:
          type: integer
          format: int64
          description: ID of the customer
          nullable: true
        status:
          type: array
          items:
            type: string
          description: Status of the order
        createdFrom:
          type: string
          format: date-time
          description: Creation datetime start date
          nullable: true
        createdTo:
          type: string
          format: date-time
          description: Creation datetime start date
          nullable: true
        limit:
          type: integer
          default: 30
        offset:
          type: integer
          default: 0

    SearchOrderResponse:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: "#/components/schemas/OrderSummary"

    SetAddressRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: |
            ID of the address:
            - If not `null`, the address associated with this ID will be associated with the order
            - If `null`, a new address will be created and associated with the order
          nullable: true
        firstName:
          type: string
          description: Customer First Name
        lastName:
          type: string
          description: Customer Last Name
        country:
          type: string
          description: Country code
        street:
          type: string
          description: Street address
          nullable: true
        cityId:
          type: integer
          format: int64
          description: ID of the city
          nullable: true
        zipCode:
          type: string
          description: ZIP code
          nullable: true
        email:
          type: string
          format: email
          description: Email address
          nullable: true

    SetShippingMethodRequest:
      type: object
      properties:
        shippingId:
          type: integer
          format: int64
          description: ID of the shipping method
        deliveryFees:
          type: number
          format: double
          description: Delivery fees
        deliveryTime:
          type: integer
          description: Delivery Time in hours
          nullable: true

    ListAddressResponse:
      type: object
      properties:
        addresses:
          type: array
          items:
            $ref: "#/components/schemas/Address"

    ChangeStatusRequest:
      type: object
      properties:
        status:
          type: string
          description: New status
        reason:
          type: string
          description: Reason of the change
          nullable: true
        comment:
          type: string
          description: Comment
          nullable: true
